################## Cloudformation RaiseTech 課題 ##################
## Author: Daisaku kato
###################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: RaiseTech EIP

Parameters:
  VPCStack:
    Type: String
    Default: RaiseTech-cfn

Resources:
#=============================================
# ElasticIP
#=============================================
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: !Sub ${VPCStack}-ec2-1a

#=============================================
# Outputs
#=============================================
Outputs:
  ElasticIP :
    Description: RaiseTech-cfn-ElasticIP
    Value: !GetAtt ElasticIP.AllocationId
    Export:
      Name: !Sub ${AWS::StackName}
