version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create CFN Stack
          command: cloudformation/deploy.sh

workflows:
  infrastructure-ci-workflow:
    jobs:
      - aws_cli
